### ISSUE TITLE
Address allowing any character or length

### ISSUE THREAD

**Issue by Mozzo1000** [gabrielchiconi/sw#14]
You can input any type of characters, not only numbers and also of any length in the address field. 
Would it not be better to only allow a correctly written ip address?

```
LABEL   ADDRESS
production      102.166.1.15
prod    wrwfawfawfwafwa
test    192.168.1.1..1
```

**Comment by fizzy-drinks** [comment]
It is possible to connect to a host via its hostname in some situations, e.g. `ssh app.example.com` or `ssh username@example.com`.

That being said, it may be beneficial to disallow spaces, or non-ASCII characters, though I am not sure if a host may permit this kind of character. Nonetheless we can verify that a hostname conforms to [RFC 1178](https://tools.ietf.org/html/rfc1178), or that an IP address is a valid IPv4 or IPv6 string.

**Comment by fizzy-drinks** [comment]
Closing for now, will reopen if this change is really necessary
